import 'package:flutter/material.dart';

abstract final class AppColorScheme {
  static ColorScheme get lightScheme => const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF585992),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFF5455A9),
    onPrimaryContainer: Color(0xFFD6D5FF),
    primaryFixed: Color(0xFFE1DFFF),
    primaryFixedDim: Color(0xFFC1C1FF),
    onPrimaryFixed: Color(0xFF0C0664),
    onPrimaryFixedVariant: Color(0xFF3C3C8F),
    secondary: Color(0xFF1D5A5D),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFF397376),
    onSecondaryContainer: Color(0xFFBBF6F9),
    secondaryFixed: Color(0xFFB2EDF0),
    secondaryFixedDim: Color(0xFF97D1D4),
    onSecondaryFixed: Color(0xFF002021),
    onSecondaryFixedVariant: Color(0xFF0B4F52),
    tertiary: Color(0xFFA13B07),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFC15221),
    onTertiaryContainer: Color(0xFFFFFBFF),
    tertiaryFixed: Color(0xFFFFDBCE),
    tertiaryFixedDim: Color(0xFFFFB599),
    onTertiaryFixed: Color(0xFF370E00),
    onTertiaryFixedVariant: Color(0xFF7F2B00),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFF93000A),
    surface: Color(0xFFFDF8F8),
    onSurface: Color(0xFF1C1B1C),
    surfaceDim: Color(0xFFDDD9D9),
    surfaceBright: Color(0xFFFDF8F8),
    surfaceContainerLowest: Color(0xFFFFFFFF),
    surfaceContainerLow: Color(0xFFF7F3F3),
    surfaceContainer: Color(0xFFF1EDED),
    surfaceContainerHigh: Color(0xFFEBE7E7),
    surfaceContainerHighest: Color(0xFFE5E1E2),
  );

  static ColorScheme get darkScheme => const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFC1C1FF),
    onPrimary: Color(0xFF242478),
    primaryContainer: Color(0xFF5455A9),
    onPrimaryContainer: Color(0xFFD6D5FF),
    primaryFixed: Color(0xFFE1DFFF),
    primaryFixedDim: Color(0xFFC1C1FF),
    onPrimaryFixed: Color(0xFF0C0664),
    onPrimaryFixedVariant: Color(0xFF3C3C8F),
    secondary: Color(0xFF97D1D4),
    onSecondary: Color(0xFF003739),
    secondaryContainer: Color(0xFF397376),
    onSecondaryContainer: Color(0xFFBBF6F9),
    secondaryFixed: Color(0xFFB2EDF0),
    secondaryFixedDim: Color(0xFF97D1D4),
    onSecondaryFixed: Color(0xFF002021),
    onSecondaryFixedVariant: Color(0xFF0B4F52),
    tertiary: Color(0xFFFFB599),
    onTertiary: Color(0xFF5A1C00),
    tertiaryContainer: Color(0xFFE66D3A),
    onTertiaryContainer: Color(0xFF461400),
    tertiaryFixed: Color(0xFFFFDBCE),
    tertiaryFixedDim: Color(0xFFFFB599),
    onTertiaryFixed: Color(0xFF370E00),
    onTertiaryFixedVariant: Color(0xFF7F2B00),
    error: Color(0xFFFFB4AB),
    onError: Color(0xFF690005),
    errorContainer: Color(0xFF93000A),
    onErrorContainer: Color(0xFFFFDAD6),
    surface: Color(0xFF141314),
    onSurface: Color(0xFFE5E1E2),
    surfaceDim: Color(0xFF141314),
    surfaceBright: Color(0xFF3A3939),
    surfaceContainerLowest: Color(0xFF0E0E0E),
    surfaceContainerLow: Color(0xFF1C1B1C),
    surfaceContainer: Color(0xFF201F20),
    surfaceContainerHigh: Color(0xFF2B2A2A),
    surfaceContainerHighest: Color(0xFF353435),
  );
}
